#!/usr/bin/env bash

IFS=$'\n' # crazy black shell magic

files=""
for file in $(git status --porcelain | cut -c 4-); do
   test -f "$file" && files="\"$file\" $files"
done

echo "white $files" | /bin/bash
