#!/usr/bin/env ruby
#
# Copyright (c) 2010 Konstantin Bender.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

require 'pathname'

root_directory = `git rev-parse --git-dir`.chomp + "/.."
working_directory = Pathname.pwd
relative_to_root_paths = `git status --ignore-submodules --porcelain | cut -c 4-`.split("\n")
absolute_paths = relative_to_root_paths.map { |path| File.expand_path(File.join(root_directory, path)) }
relative_paths = absolute_paths.map { |path| Pathname.new(path).relative_path_from(working_directory).to_s }
valid_paths = relative_paths.select { |path| `test -f #{path}` }
command = "white " + valid_paths.join(" ")
system command