#!/usr/bin/env ruby

require 'pathname'

root_directory = `git rev-parse --git-dir`.chomp + "/.."
working_directory = Pathname.pwd
relative_to_root_paths = `git status --ignore-submodules --porcelain | cut -c 4-`.split("\n")
absolute_paths = relative_to_root_paths.map { |path| File.expand_path(File.join(root_directory, path)) }
relative_paths = absolute_paths.map { |path| Pathname.new(path).relative_path_from(working_directory).to_s }
quoted_paths = relative_paths.map { |path| "\"#{path}\""}
valid_paths = quoted_paths.select { |path| `test -f #{path}` }
command = "white " + valid_paths.join(" ")
system command
